CREATE DATABASE QLHH

USE QLHH

CREATE TABLE KHACHHANG 
(
	MAKHACHHANG VARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKHACHHANG)
)
CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(10) NOT NULL,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20),
	LUONGCOBAN MONEY NOT NULL,
	PHUCAP MONEY NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY  (MANHANVIEN)
)
CREATE TABLE NHACUNGCAP
(
	MACONGTY VARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MACONGTY)
)
CREATE TABLE LOAIHANG
(
	MALOAIHANG VARCHAR(10) NOT NULL,
	TENLOAIHANG NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_LOAIHANG PRIMARY KEY (MALOAIHANG)
)
CREATE TABLE MATHANG 
(
	MAHANG VARCHAR(10) NOT NULL,
	TENHANG NVARCHAR(100) NOT NULL,
	MACONGTY VARCHAR(10) NOT NULL,
	MALOAIHANG VARCHAR(10) NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	DONVITINH NVARCHAR(20) NOT NULL,
	GIAHANG MONEY NOT NULL,
	CONSTRAINT PK_MATHANG PRIMARY KEY (MAHANG),
	CONSTRAINT FK_MATHANG_MACONGTY FOREIGN KEY (MACONGTY) REFERENCES DBO.NHACUNGCAP (MACONGTY),
	CONSTRAINT FK_MATHANG_MALOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES DBO.LOAIHANG (MALOAIHANG),
)
CREATE  TABLE DONDATHANG
(
	SOHOADON VARCHAR(10) NOT NULL,
	MAKHACHHANG VARCHAR(10) NOT NULL,
	MANHANVIEN VARCHAR(10) NOT NULL,
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(100),
	CONSTRAINT PK_DONDATHANG PRIMARY KEY (SOHOADON),
	CONSTRAINT FK_DONDATHANG_MAKHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES DBO.KHACHHANG (MAKHACHHANG),
	CONSTRAINT FK_DONDATHANG_MANHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES DBO.NHANVIEN (MANHANVIEN),
)
CREATE TABLE CHITIETDATHANG
(
	SOHOADON VARCHAR(10) NOT NULL,
	MAHANG VARCHAR(10) NOT NULL,
	GIABAN MONEY NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	MUCGIAMGIA DECIMAL(4,2) NOT NULL,
	CONSTRAINT PK_CHITIETDATHANG PRIMARY KEY (SOHOADON, MAHANG),
	CONSTRAINT FK_CHITIETDATHANG_SOHOADON FOREIGN KEY (SOHOADON) REFERENCES DBO.DONDATHANG (SOHOADON),
	CONSTRAINT FK_CHITIETDATHANG_MAHANG FOREIGN KEY (MAHANG) REFERENCES DBO.MATHANG (MAHANG),
)
