create database QLSV
go 

CREATE TABLE KHOA
(
	MaKhoa VARCHAR(10) NOT NULL,
	TenKhoa NVARCHAR(50) NOT NULL,
	SL_CBGD SMALLINT NOT NULL,
	CONSTRAINT PK_KHOA PRIMARY KEY (MaKhoa)
)

CREATE TABLE SINHVIEN
(
	MSSV VARCHAR(5) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	GioiTinh VARCHAR(5) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	DienThoai VARCHAR(20),
	MaKhoa VARCHAR(10),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY (MSSV),
	CONSTRAINT FK_SINHVIEN FOREIGN KEY (MaKhoa) REFERENCES dbo.KHOA (MaKhoa)
)

CREATE TABLE GIAOVIEN
(
	MaGV VARCHAR(5) NOT NULL,
	TenGV NVARCHAR(50) NOT NULL,
	MaKhoa VARCHAR(10),
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MaGV),
	CONSTRAINT FK_GIAOVIEN FOREIGN KEY (MaKhoa) REFERENCES DBO.KHOA (MaKhoa)
)

CREATE TABLE MONHOC
(
	MaMH VARCHAR(5) NOT NULL,
	TenMH NVARCHAR(50) NOT NULL,
	SoTC SMALLINT NOT NULL,
	CONSTRAINT PK_MONHOC PRIMARY KEY (MaMH)
)

CREATE TABLE GIANGDAY
(
	MaKhoaHoc VARCHAR(5) NOT NULL,
	MaGV VARCHAR(5),
	MaMH VARCHAR(5),
	HocKy SMALLINT NOT NULL,
	Nam INT NOT NULL,
	CONSTRAINT PK_GIANGDAY PRIMARY KEY (MaKhoaHoc),
	CONSTRAINT FK_GIANGDAY_MaGV FOREIGN  KEY (MaGV) REFERENCES DBO.GIAOVIEN (MaGV),
	CONSTRAINT FK_GIANGDAY_MaMH FOREIGN  KEY (MaMH) REFERENCES DBO.MONHOC (MaMH),
)
create table KETQUA
(
	MaSV  varchar(5) not null,
	MaKhoaHoc varchar(5) not null,
	Diem decimal(3,1) not null,
	constraint PK_KETQUA primary key (MaSV, MaKhoaHoc),
	constraint FG_KETQUA_MaSV foreign key (MaSV) references dbo.SINHVIEN (MSSV),
	constraint FG_KETQUA_MaKhoaHoc foreign key (MaKhoaHoc) references dbo.GIANGDAY (MaKhoaHoc)
)