CREATE DATABASE QLDA
GO

CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(5) NOT NULL,
	TENPB NVARCHAR(50) NOT NULL,
	TRUONGPHONG VARCHAR(5) NOT NULL,
	NG_NHANCHUC DATE NOT NULL,
	CONSTRAINT PK_PHONGBAN PRIMARY KEY (MAPB)
)
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(5) NOT NULL,
	HONV NVARCHAR(20) NOT NULL,
	TENLOT NVARCHAR(20) NOT NULL,
	TENNV NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	PHAI VARCHAR(5) NOT NULL,
	LUONG DECIMAL(10,2) NOT NULL,
	MAPB VARCHAR(5) NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
	CONSTRAINT FK_NHANVIEN FOREIGN KEY (MAPB) REFERENCES DBO.PHONGBAN (MAPB)
)
CREATE TABLE DEAN
(
	MADA VARCHAR(5) NOT NULL,
	TENDA NVARCHAR(50) NOT NULL,
	DDIEM_DA NVARCHAR(100) NOT NULL,
	MAPB VARCHAR(5) NOT NULL,
	CONSTRAINT PK_DEAN PRIMARY KEY (MADA),
	CONSTRAINT FK_DEEAN FOREIGN KEY (MAPB) REFERENCES DBO.PHONGBAN (MAPB)
)
CREATE TABLE  DDIEMPB
(
	MAPB VARCHAR(5) NOT NULL,
	DIADIEM NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_DDIEMPB PRIMARY KEY (MAPB, DIADIEM),
	CONSTRAINT FK_DDIEMPB FOREIGN KEY (MAPB) REFERENCES DBO.PHONGBAN (MAPB)
)
CREATE TABLE THANNHAN
(
	MANV VARCHAR(5) NOT NULL,
	TENTN NVARCHAR(30) NOT NULL,
	PHAI VARCHAR(5) NOT NULL,
	NGAYSINH DATE NOT NULL,
	QUANHE NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_THANNHAN PRIMARY KEY (MANV, TENTN),
	CONSTRAINT FK_THANNHAN FOREIGN KEY (MANV) REFERENCES DBO.NHANVIEN (MANV)
)
CREATE TABLE PHANCONG
(
	MANV VARCHAR(5) NOT NULL,
	MADA VARCHAR(5) NOT NULL,
	THOIGIAN DECIMAL(5,1) NOT NULL,
	CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV, MADA),
	CONSTRAINT FK_PHANCONG_MANV FOREIGN KEY (MANV) REFERENCES DBO.NHANVIEN (MANV),
	CONSTRAINT FK_PHANCONG_MADA FOREIGN KEY (MADA) REFERENCES DBO.DEAN (MADA)
)
